/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.4/userguide/tutorial_java_projects.html
 */

allprojects {
    repositories {
        mavenLocal()
        maven {
            url = uri("http://maven.aliyun.com/nexus/content/groups/public/")
        }
        maven {
            url = uri("http://maven.aliyun.com/nexus/content/repositories/jcenter")
        }
        mavenCentral()

    }
}
plugins {
    // Apply the java plugin to add support for Java
    java
    scala

    // Apply the application plugin to add support for building a CLI application
    application
}

dependencies {
    
    implementation("org.apache.spark:spark-core_2.12:2.4.4")
    implementation("org.apache.spark:spark-sql_2.12:2.4.4")
    
}

application {
    // Define the main class for the application
    mainClassName = "com.vgc.App"
}

val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
}
